<?php
	$emotionListDefault = array(
		array(
			'groupname' => __('颜文字', 'argon'), 
			'list' => array(
				array('type' => 'text', 'text' => "|´・ω・)ノ"),
				array('type' => 'text', 'text' => "ヾ(≧∇≦*)ゝ"),
				array('type' => 'text', 'text' => "(☆ω☆)"),
				array('type' => 'text', 'text' => "（╯‵□′）╯︵┴─┴"),
				array('type' => 'text', 'text' => "￣﹃￣"),
				array('type' => 'text', 'text' => "(/ω＼)"),
				array('type' => 'text', 'text' => "∠( ᐛ 」∠)＿"),
				array('type' => 'text', 'text' => "(๑•̀ㅁ•́ฅ)"),
				array('type' => 'text', 'text' => "→_→"),
				array('type' => 'text', 'text' => "୧(๑•̀⌄•́๑)૭"),
				array('type' => 'text', 'text' => "٩(ˊᗜˋ*)و"),
				array('type' => 'text', 'text' => "(ノ°ο°)ノ"),
				array('type' => 'text', 'text' => "(´இ皿இ｀)"),
				array('type' => 'text', 'text' => "⌇●﹏●⌇"),
				array('type' => 'text', 'text' => "(ฅ´ω`ฅ)"),
				array('type' => 'text', 'text' => "(╯°A°)╯︵○○○"),
				array('type' => 'text', 'text' => "φ(￣∇￣o)"),
				array('type' => 'text', 'text' => "ヾ(´･ ･｀｡)ノ\""),
				array('type' => 'text', 'text' => "( ง ᵒ̌皿ᵒ̌)ง⁼³₌₃"),
				array('type' => 'text', 'text' => "(ó﹏ò｡)"),
				array('type' => 'text', 'text' => "Σ(っ °Д °;)っ"),
				array('type' => 'text', 'text' => "( ,,´･ω･)ﾉ\"(´っω･｀｡)"),
				array('type' => 'text', 'text' => "╮(╯▽╰)╭"),
				array('type' => 'text', 'text' => "o(*////▽////*)q"),
				array('type' => 'text', 'text' => "＞﹏＜"),
				array('type' => 'text', 'text' => "( ๑´•ω•) \"(ㆆᴗㆆ)")
			)
		),
		array(
			'groupname' => 'Emoji', 
			'list' => array(
				array('type' => 'text', 'text' => "😂"),
				array('type' => 'text', 'text' => "😀"),
				array('type' => 'text', 'text' => "😅"),
				array('type' => 'text', 'text' => "😊"),
				array('type' => 'text', 'text' => "🙂"),
				array('type' => 'text', 'text' => "🙃"),
				array('type' => 'text', 'text' => "😌"),
				array('type' => 'text', 'text' => "😍"),
				array('type' => 'text', 'text' => "😘"),
				array('type' => 'text', 'text' => "😜"),
				array('type' => 'text', 'text' => "😝"),
				array('type' => 'text', 'text' => "😏"),
				array('type' => 'text', 'text' => "😒"),
				array('type' => 'text', 'text' => "🙄"),
				array('type' => 'text', 'text' => "😳"),
				array('type' => 'text', 'text' => "😡"),
				array('type' => 'text', 'text' => "😔"),
				array('type' => 'text', 'text' => "😫"),
				array('type' => 'text', 'text' => "😱"),
				array('type' => 'text', 'text' => "😭"),
				array('type' => 'text', 'text' => "💩"),
				array('type' => 'text', 'text' => "👻"),
				array('type' => 'text', 'text' => "🙌"),
				array('type' => 'text', 'text' => "🖕"),
				array('type' => 'text', 'text' => "👍"),
				array('type' => 'text', 'text' => "👫"),
				array('type' => 'text', 'text' => "👬"),
				array('type' => 'text', 'text' => "👭"),
				array('type' => 'text', 'text' => "🌚"),
				array('type' => 'text', 'text' => "🌝"),
				array('type' => 'text', 'text' => "🙈"),
				array('type' => 'text', 'text' => "💊"),
				array('type' => 'text', 'text' => "😶"),
				array('type' => 'text', 'text' => "🙏"),
				array('type' => 'text', 'text' => "🍦"),
				array('type' => 'text', 'text' => "🍉"),
				array('type' => 'text', 'text' => "😣")
			)
		),
		array(
			'groupname' => '小恐龙', 
			'list' => array(
				array('type' => 'sticker', 'code' => 'dinosaur-shy', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/1.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-daze', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/2.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-sweat', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/3.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-proud', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/4.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-powerless', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/5.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-pouting', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/6.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-eating', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/7.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-ok', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/8.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-doubt', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/9.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-depressed', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/10.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-close-eyes', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/11.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-sleeping', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/12.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-puzzled', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/13.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-agree', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/14.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-crazy', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/15.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-angry', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/16.jpg')
			)
		),
		array(
			'groupname' => '花!', 
			'list' => array(
				array('type' => 'sticker', 'code' => 'flower-flower', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/1.jpg'),
				array('type' => 'sticker', 'code' => 'flower-grass', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/2.jpg'),
				array('type' => 'sticker', 'code' => 'flower-leaf', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/3.jpg'),
				array('type' => 'sticker', 'code' => 'flower-star', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/4.jpg'),
				array('type' => 'sticker', 'code' => 'flower-sun', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/5.jpg'),
				array('type' => 'sticker', 'code' => 'flower-moon', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/6.jpg'),
				array('type' => 'sticker', 'code' => 'flower-water', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/7.jpg'),
				array('type' => 'sticker', 'code' => 'flower-heihei', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/8.jpg'),
				array('type' => 'sticker', 'code' => 'flower-lemon', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/9.jpg'),
				array('type' => 'sticker', 'code' => 'flower-birthday', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/10.jpg'),
				array('type' => 'sticker', 'code' => 'flower-sea', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/11.jpg'),
				array('type' => 'sticker', 'code' => 'flower-vegetable', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/12.jpg'),
				array('type' => 'sticker', 'code' => 'flower-tile', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/13.jpg'),
				array('type' => 'sticker', 'code' => 'flower-utf', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/14.jpg'),
			),
			'description' => 'Source: github.com/k4yt3x/flowerhd'
		),
		array(
			'groupname' => '邦',
			'list' => array(
				array('type' => 'sticker', 'code' => 'BanGDream_香澄-期待', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_香澄-期待.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_多惠-震惊', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_多惠-震惊.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_里美-害羞', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_里美-害羞.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_沙绫-没问题', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_沙绫-没问题.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_有咲-汗', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_有咲-汗.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_兰-嫌弃', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_兰-嫌弃.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_摩卡-满足', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_摩卡-满足.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_绯玛丽-宠溺', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_绯玛丽-宠溺.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_巴-尴尬', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_巴-尴尬.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_鸫-讨厌', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_鸫-讨厌.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_心-好耶', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_心-好耶.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_薰-送花', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_薰-送花.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_育美-高兴', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_育美-高兴.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_花音-害怕', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_花音-害怕.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_米歇尔-DJ', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_米歇尔-DJ.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_彩-躲藏', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_彩-躲藏.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_日菜-挽留', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_日菜-挽留.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_千圣-暗中观察', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_千圣-暗中观察.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_麻弥-紧张', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_麻弥-紧张.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_伊芙-比心', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_伊芙-比心.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_友希那-满足', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_友希那-满足.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_纱夜-不高兴', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_纱夜-不高兴.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_莉莎-点赞', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_莉莎-点赞.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_亚子-打call', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_亚子-打call.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_燐子-懵', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_燐子-懵.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_真白-惊慌', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_真白-惊慌.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_透子-心虚', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_透子-心虚.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_七深-安详', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_七深-安详.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_筑紫-不满', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_筑紫-不满.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_瑠唯-优雅', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_瑠唯-优雅.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_LAYER-拽', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_LAYER-拽.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_LOCK-不可以', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_LOCK-不可以.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_MASKING-来了', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_MASKING-来了.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_PAREO-太好了', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_PAREO-太好了.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_CHU²-阴谋', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_CHU²-阴谋.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_灯-放松', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_灯-放松.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_爱音-不解', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_爱音-不解.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_乐奈-困', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_乐奈-困.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_爽世-微笑', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_爽世-微笑.png'),
				array('type' => 'sticker', 'code' => 'BanGDream_立希-怒', 'src' => $GLOBALS['assets_path'] . '/stickers/BanGDream/BanGDream_立希-怒.png'),
			),
			'description' => '仅供学习和交流使用，版权归原作者所有'
		),
		array(
			'groupname' => '狗',
			'list' => array(
				array('type' => 'sticker', 'code' => 'Mygo表情包_害羞', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_害羞.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_生气', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_生气.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_发送消息', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_发送消息.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_抹茶芭菲', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_抹茶芭菲.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_请点单', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_请点单.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_不要吵架', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_不要吵架.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_Love', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_Love.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_让我看看', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_让我看看.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_溜了溜了', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_溜了溜了.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_那我呢？', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_那我呢？.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_创作中', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_创作中.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_探头', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_探头.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_为什么！', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_为什么！.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_刚睡醒', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_刚睡醒.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_哈？', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_哈？.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_忧郁', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_忧郁.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_不会吧？', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_不会吧？.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_大哭', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_大哭.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_有趣的女人', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_有趣的女人.png'),
				array('type' => 'sticker', 'code' => 'Mygo表情包_Block!', 'src' => $GLOBALS['assets_path'] . '/stickers/Mygo表情包/Mygo表情包_Block!.png'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_泣', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_泣.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_哈？', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_哈？.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_比心', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_比心.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_emo', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_emo.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_探头', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_探头.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_鼓掌', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_鼓掌.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_微笑', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_微笑.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_生气', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_生气.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_剪切', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_剪切.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_傲娇', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_傲娇.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_逃跑', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_逃跑.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_瞪', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_瞪.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_rua猫', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_rua猫.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_观察', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_观察.gif'),
				array('type' => 'sticker', 'code' => '良辰共此曲动态表情包_思考', 'src' => $GLOBALS['assets_path'] . '/stickers/良辰共此曲动态表情包/良辰共此曲动态表情包_思考.gif'),
			),
			'description' => 'MyGO!!!!!是BanG Dream!系列不可分割的一部分。仅供学习和交流使用，版权归原作者所有'
		),
		array(
			'groupname' => '哭',
			'list' => array(
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_摇滚', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_摇滚.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_倔', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_倔.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_生气', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_生气.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_坏笑', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_坏笑.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_愣住', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_愣住.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_哭泣', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_哭泣.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_噫', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_噫.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_开车', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_开车.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_哈哈', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_哈哈.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_哈？', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_哈？.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_吐舌', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_吐舌.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_献花', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_献花.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_沉默', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_沉默.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_wink', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_wink.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_乐', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_乐.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_害羞', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_害羞.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_泪目', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_泪目.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_不行', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_不行.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_郁闷', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_郁闷.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_咬牙切齿', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_咬牙切齿.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_胸有成竹', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_胸有成竹.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_比心', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_比心.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_拜托', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_拜托.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_嘲笑', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_嘲笑.png'),
				array('type' => 'sticker', 'code' => '少女乐队的呐喊表情包_拜拜', 'src' => $GLOBALS['assets_path'] . '/stickers/少女乐队的呐喊表情包/少女乐队的呐喊表情包_拜拜.png'),
			),
			'description' => '仅供学习和交流使用，版权归原作者所有'
		),
		array(
			'groupname' => '滚',
			'list' => array(
				array('type' => 'sticker', 'code' => '孤独摇滚_社恐', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_社恐.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_喜欢', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_喜欢.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_打', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_打.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_贴贴', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_贴贴.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_COOL', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_COOL.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_微笑', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_微笑.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_好孩子', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_好孩子.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_哇', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_哇.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_偷看', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_偷看.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_害羞', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_害羞.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_气鼓鼓', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_气鼓鼓.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_憋笑', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_憋笑.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_吃草', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_吃草.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_可爱', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_可爱.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_大吃特吃', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_大吃特吃.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_嘘', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_嘘.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_投钱', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_投钱.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_害怕', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_害怕.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_完了呀', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_完了呀.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_加油', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_加油.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_拍手', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_拍手.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_惊呆', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_惊呆.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_威胁', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_威胁.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_摸头', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_摸头.png'),
				array('type' => 'sticker', 'code' => '孤独摇滚_举起手来', 'src' => $GLOBALS['assets_path'] . '/stickers/孤独摇滚/孤独摇滚_举起手来.png'),
			),
			'description' => '仅供学习和交流使用，版权归原作者所有'
		),
	);
?>